/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf.uva.ipc.vista;

import inf.uva.ipc.main.Main;
import inf.uva.ipc.modelo.Modelo;
import java.awt.Color;


/**
 *
 * @author victo, alvdela
 */
public class VistaCambiarPin extends javax.swing.JFrame {

    private Modelo modelo;
    private ControladorCambiarPin controlador;
    
    /**
     * Crea la vista de cambiar pin y su controlador.
     * @param modelo, modelo del sistema
     */
    public VistaCambiarPin(Modelo modelo) {
        initComponents();
        this.modelo = modelo;
        controlador = new ControladorCambiarPin(this,modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        resultLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pinAntField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pinNewField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pinAgainField = new javax.swing.JTextField();

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cambiar pin de la tarjeta:");
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Cambiar pin de la tarjeta:");
        jPanel7.add(jLabel6);

        jPanel4.add(jPanel7);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("El pin debe contener 4 digitos");
        jPanel8.add(jLabel5);

        jPanel4.add(jPanel8);

        jPanel6.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 200, 5));

        confirmButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        confirmButton.setText("Confirmar");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        jPanel3.add(confirmButton);

        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel3.add(cancelButton);

        jPanel6.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel5.setLayout(new java.awt.BorderLayout());

        resultLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resultLabel.setText(" ");
        resultLabel.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jPanel5.add(resultLabel, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridLayout(3, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Introduzca el pin antiguo:");
        jPanel2.add(jLabel2);

        pinAntField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pinAntField.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        pinAntField.setSelectionEnd(4);
        pinAntField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinAntFieldActionPerformed(evt);
            }
        });
        jPanel2.add(pinAntField);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Introduzca el pin nuevo:");
        jPanel2.add(jLabel3);

        pinNewField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(pinNewField);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Repita el pin nuevo:");
        jPanel2.add(jLabel4);

        pinAgainField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(pinAgainField);

        jPanel5.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        controlador.procesarConfirmarPin();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        controlador.procesarCancelButton();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void pinAntFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinAntFieldActionPerformed

    }//GEN-LAST:event_pinAntFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField pinAgainField;
    private javax.swing.JTextField pinAntField;
    private javax.swing.JTextField pinNewField;
    private javax.swing.JLabel resultLabel;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Regresa al menu principal.
     */
    public void regresaAMenu(){
        Main.getStateMachine().abrirVentanaMenu();
    }
    
    /**
    * Devuelve el string del pin antiguo.
    * @return campo pin antiguo
    */
    public String devuelvePinAnt(){
        return pinAntField.getText();
    }
    /**
    * Indicar el error, con el mensaje correspondiente.
    * @param error, mensaje de error.
    */
    public void setError(String error){
        resultLabel.setForeground(Color.red);
        resultLabel.setText(error);
        //cleanPin();
    }
    /**
    * Devuelve el string del pin nuevo.
    * @return campo del pin nuevo 1.
    */
    public String devuelvePinNuev(){
        return pinNewField.getText();
    }
    /**
    * Devuelve de nuevo el string del pin nuevo.
    * @return campo del pin nuevo 2.
    */
    public String devuelvePinNuev2(){
        return pinAgainField.getText();
    } 
    
    /**
     * Pone en blanco los campos de texto.
     */
    public void cleanPin(){
        pinAntField.setText("");
        pinNewField.setText("");
        pinAgainField.setText("");
    }
    
    /**
    * Muestra un mensaje de que se ha cambiado el pin.
    */
    public void cambioCorrecto() {
        resultLabel.setForeground(Color.green);
        resultLabel.setText("Pin cambiado con éxio.");
    }
}
