/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf.uva.ipc.vista;

import inf.uva.ipc.main.Main;
import inf.uva.ipc.modelo.Modelo;
import java.awt.Color;

/**
 *
 * @author viccall, alvdela
 */
public class VistaTransferencia extends javax.swing.JFrame {

    private Modelo modelo;
    private ControladorTransferencia controlador;
    
    /**
     * Crea la vista hacer tansferencia y su controlador.
     * @param modelo, modelo del sistema.
     */
    public VistaTransferencia(Modelo modelo) {
        initComponents();
        this.modelo = modelo;
        controlador = new ControladorTransferencia(this, modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        titularField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cuentaField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        conceptoField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cantidadField = new javax.swing.JTextField();
        resultText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 200, 5));

        confirmButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        confirmButton.setText("Confirmar");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        jPanel3.add(confirmButton);

        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel3.add(cancelButton);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("   Transferencia bancaria:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(5, 2));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("   Nombre del titular:");
        jPanel1.add(jLabel2);

        titularField.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(titularField);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("   Número de cuenta:");
        jPanel1.add(jLabel3);

        cuentaField.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(cuentaField);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("   Concepto:");
        jPanel1.add(jLabel7);

        conceptoField.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        conceptoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conceptoFieldActionPerformed(evt);
            }
        });
        jPanel1.add(conceptoField);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("   Cantidad a transferir:");
        jPanel1.add(jLabel4);

        cantidadField.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cantidadField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadFieldActionPerformed(evt);
            }
        });
        jPanel1.add(cantidadField);

        resultText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(resultText);

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantidadFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        controlador.procesarCancelButton();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        controlador.procesarConfirmar();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void conceptoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conceptoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conceptoFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField cantidadField;
    private javax.swing.JTextField conceptoField;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField cuentaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel resultText;
    private javax.swing.JTextField titularField;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Regresa al menu principal.
     */
    public void regresaAMenu(){
        Main.getStateMachine().abrirVentanaMenu();
    }
    
    /**
    * Devuelve un string con la informacion que haya en titularField
    * @return campo del titular
    */
    public String getTitular(){
        return titularField.getText();
    }
    
    /**
     * Devuelve un string con la informacion que haya en cuentaField
     * @return campo de la cuenta
     */
    public String getCuenta(){
        return cuentaField.getText();
    }
    
    /**
     * Devuelve un string con la informacion que haya en cantidadField
     * @return campo de la cantidad
     */
    public String getCantidad(){
        return cantidadField.getText();
    }
    
    /**
     * Devuelve un string con la informacion que haya en conceptoField
     * @return campo del concepto.
     */
    public String getConcepto(){
        return conceptoField.getText();
    }
    
    /**
     * Lanza manesajes de error a traves de una etiqueta.
     * @param error, mensaje de error.
     */
    public void setError(String error){
        resultText.setForeground(Color.red);
        resultText.setText(error);
        //clear();
    }
      
    /**
     * Borra todos los campos.
     */
    public void clear(){
        titularField.setText("");
        cuentaField.setText("");
        cantidadField.setText("");
        conceptoField.setText("");
    }
    
    /**
     * Lanza un mensaje de exito al realizar una transferencia de forma correcta.
     */
    public void setCorrecto(){
        resultText.setForeground(Color.green);
        resultText.setText("Transferencia realizada con exito");
        clear();
    }
}
