/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf.uva.ipc.vista;

import inf.uva.ipc.main.Main;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author viccall, alvdela
 */
public class VistaMenu extends javax.swing.JFrame {

    private ControladorMenu controlador;
    
    /**
     * Crea la vista del menu y su controlador.
     */
    public VistaMenu() {
        initComponents();
        ImageIcon icono = new ImageIcon("src/inf/uva/ipc/vista/infuva.png");
        logo.setIcon(new ImageIcon(icono.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
        controlador = new ControladorMenu(this);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        botonCajero = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        botonCambiar = new javax.swing.JButton();
        botonTransf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel1.add(logo);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido a la red UVaCash");
        jPanel3.add(jLabel1);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("¿Que desea realizar?");
        jPanel5.add(jLabel2);

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        botonCajero.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        botonCajero.setText("Abrir Cajero");
        botonCajero.setMaximumSize(new java.awt.Dimension(1000, 1000));
        botonCajero.setPreferredSize(new java.awt.Dimension(250, 85));
        botonCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCajeroActionPerformed(evt);
            }
        });
        jPanel7.add(botonCajero);

        jPanel6.add(jPanel7);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        botonCambiar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        botonCambiar.setText("Cambiar PIN");
        botonCambiar.setPreferredSize(new java.awt.Dimension(150, 85));
        botonCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarActionPerformed(evt);
            }
        });
        jPanel8.add(botonCambiar);

        botonTransf.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        botonTransf.setText("<html> Hacer Transferencia");
        botonTransf.setPreferredSize(new java.awt.Dimension(150, 85));
        botonTransf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTransfActionPerformed(evt);
            }
        });
        jPanel8.add(botonTransf);

        jPanel6.add(jPanel8);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCajeroActionPerformed
        controlador.procesarBotonCajero();
    }//GEN-LAST:event_botonCajeroActionPerformed

    private void botonCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarActionPerformed
        controlador.procesarBotonCambiarPin();
    }//GEN-LAST:event_botonCambiarActionPerformed

    private void botonTransfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTransfActionPerformed
        controlador.procesarBotonTransferencia();
    }//GEN-LAST:event_botonTransfActionPerformed
    
    /**
     * Cambia la ventana a la del cajero
     */
    public void cambiarACajero(){
        Main.getStateMachine().abrirVentanaCajero();
    }
    
    /**
     * Cambia la ventana a la de cambiar el pin
     */
    public void cambiarACambiarPin(){
        Main.getStateMachine().abrirVentanaCambiarPin();
    }
    
    /**
     * Cambia la ventana a la de realizar transferencia
     */
    public void cambiarATrasferencia(){
        Main.getStateMachine().abrirVentanaTransferencia();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCajero;
    private javax.swing.JButton botonCambiar;
    private javax.swing.JButton botonTransf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
